### ISSUE TITLE
BLOCKER - Service discovery isn't working

### ISSUE THREAD

**Issue by rasheedamir** [stakater/kat#1]
Still our networking has an issue as the basic thing like service discovery by name which is the key feature of k8s is not working!

fabric8 console is trying to reach gogs by service name; it should work but its failing

```
javax.ws.rs.ProcessingException: java.net.UnknownHostException: UnknownHostException invoking http://gogs/api/v1/user/repos: gogs
	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:601)
	at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:578)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:758)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:235)
	at com.sun.proxy.$Proxy160.createRepository(Unknown Source)
	at io.fabric8.repo.git.GitRepoClientSupport.createRepository(GitRepoClientSupport.java:101)
	at io.fabric8.project.support.BuildConfigHelper.importNewGitProject(BuildConfigHelper.java:124)
	at io.fabric8.forge.rest.main.GitCommandCompletePostProcessor.firePostCompleteActions(GitCommandCompletePostProcessor.java:130)
	at io.fabric8.forge.rest.CommandsResource.doExecute(CommandsResource.java:455)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:349)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:345)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:672)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:633)
	at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:252)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:299)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:218)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:274)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: UnknownHostException invoking http://gogs/api/v1/user/repos: gogs
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1377)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1361)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:651)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:672)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:756)
	... 57 more
Caused by: java.net.UnknownHostException: gogs
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:236)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1320)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1280)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:267)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
	at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:69)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1333)
	... 63 more
```

**Comment by rasheedamir** [comment]
containers on master

```
CONTAINER ID        IMAGE                                                                                           COMMAND                  CREATED             STATUS              PORTS               NAMES
e6cdb3b40b76        weaveworks/weave-kube@sha256:77ffa5e6d1c471e1d921d110e19b579d2c78879b53ac09d7732e5afe441074d2   "/home/weave/launch.s"   About an hour ago   Up About an hour                        k8s_weave_weave-net-9rg0x_kube-system_bba2e5ae-791c-11e7-87d8-0a1a0e915450_0
e2f1a9caf5b3        weaveworks/weave-npc@sha256:5feb89098e84258afaadd878c41e5029ff1baa68579fe75cfca275b24caa4020    "/usr/bin/weave-npc"     About an hour ago   Up About an hour                        k8s_weave-npc_weave-net-9rg0x_kube-system_bba2e5ae-791c-11e7-87d8-0a1a0e915450_0
11dd6ebb16dd        gcr.io/google_containers/pause-amd64:3.0                                                        "/pause"                 About an hour ago   Up About an hour                        k8s_POD_weave-net-9rg0x_kube-system_bba2e5ae-791c-11e7-87d8-0a1a0e915450_0
```

**Comment by rasheedamir** [comment]
containers on one node

```
CONTAINER ID        IMAGE                                                                                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
11d537383dc5        prom/prometheus@sha256:359aa4eb4f210f6012ac412bc48ea450e2d30fd23a2652d3df6bc311f1936c73                           "/bin/prometheus -con"   11 minutes ago      Up 11 minutes                           k8s_prometheus_prometheus-1485758666-71hb4_digitaldealer_89520f59-7929-11e7-87d8-0a1a0e915450_3
5a15882a472f        jimmidyson/configmap-reload@sha256:2d40c2eaa6f435b2511d0cfc5f6c0a681eeb2eaa455a5d5ac25f88ce5139986e               "/configmap-reload -v"   12 minutes ago      Up 12 minutes                           k8s_configmap-reload_prometheus-1485758666-71hb4_digitaldealer_89520f59-7929-11e7-87d8-0a1a0e915450_0
f06d8dadf1fc        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 12 minutes ago      Up 12 minutes                           k8s_POD_prometheus-1485758666-71hb4_digitaldealer_89520f59-7929-11e7-87d8-0a1a0e915450_0
844ef7e0fc26        registry@sha256:f5552e60ffd56fecbe2f04b61a3089a9cd755bd9352b6b5ab22cf2208af6a3a8                                  "/entrypoint.sh /etc/"   12 minutes ago      Up 12 minutes                           k8s_fabric8-docker-registry_fabric8-docker-registry-125311296-pgfv3_digitaldealer_a69239ad-7928-11e7-87d8-0a1a0e915450_0
81bc94affefa        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 12 minutes ago      Up 12 minutes                           k8s_POD_fabric8-docker-registry-125311296-pgfv3_digitaldealer_a69239ad-7928-11e7-87d8-0a1a0e915450_0
ab3f9e12f235        fabric8/jenkinshift@sha256:1ff07e6098cf1c40cb3bd72b8aff6e977b7791ad3aa4b6df660fbf5a29ee36dc                       "/bin/sh -c jenkinshi"   18 minutes ago      Up 18 minutes                           k8s_jenkinshift_fabric8-3873669821-dnt3v_digitaldealer_aa096167-7928-11e7-87d8-0a1a0e915450_0
06fa5cea7f46        fabric8/fabric8-console@sha256:620727abe356f9c6e82f59c2778e6f93e32f81576385b179fa6b730221c88334                   "/kuisp -p 9090 -c /s"   18 minutes ago      Up 18 minutes                           k8s_fabric8_fabric8-3873669821-dnt3v_digitaldealer_aa096167-7928-11e7-87d8-0a1a0e915450_0
b8329370ff96        fabric8/exposecontroller@sha256:598c8bf1ae03a8601d1dfbe9ac9889d1654c8c816d76f88cb0a39882ed884b7e                  "/exposecontroller"      18 minutes ago      Up 18 minutes                           k8s_exposecontroller_exposecontroller-3416897539-swh39_digitaldealer_ad30626d-7928-11e7-87d8-0a1a0e915450_0
197a1cb1b247        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 18 minutes ago      Up 18 minutes                           k8s_POD_exposecontroller-3416897539-swh39_digitaldealer_ad30626d-7928-11e7-87d8-0a1a0e915450_0
71f76dfd1dfd        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 18 minutes ago      Up 18 minutes                           k8s_POD_fabric8-3873669821-dnt3v_digitaldealer_aa096167-7928-11e7-87d8-0a1a0e915450_0
cd9932f805e2        prom/node-exporter@sha256:ffc3e0adf58771cb2097aa0b074a6fe68b4925ba75c2e1c41f41ae656eebee11                        "/bin/node_exporter -"   18 minutes ago      Up 18 minutes                           k8s_node-exporter_node-exporter-v5nb8_digitaldealer_a9307d07-7928-11e7-87d8-0a1a0e915450_0
d66b7efc70b0        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 18 minutes ago      Up 18 minutes                           k8s_POD_node-exporter-v5nb8_digitaldealer_a9307d07-7928-11e7-87d8-0a1a0e915450_0
1b64010ae919        fabric8/fluentd-kubernetes@sha256:46bef4e8e726dee32600658d784244ee92fee7b84530315ca0a3e347e4096fd4                "/start-fluentd"         18 minutes ago      Up 18 minutes                           k8s_fluentd_fluentd-mtrk8_digitaldealer_a7b94cd9-7928-11e7-87d8-0a1a0e915450_0
f15146e07344        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 18 minutes ago      Up 18 minutes                           k8s_POD_fluentd-mtrk8_digitaldealer_a7b94cd9-7928-11e7-87d8-0a1a0e915450_0
1c037c60fc7a        gcr.io/google_containers/defaultbackend@sha256:ee3aa1187023d0197e3277833f19d9ef7df26cee805fef32663e06c7412239f9   "/server"                19 minutes ago      Up 19 minutes                           k8s_default-backend_default-backend-445292540-f2l7h_nginx-ingress_8d8ff3b4-7928-11e7-87d8-0a1a0e915450_0
cb4a9464f1f4        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 19 minutes ago      Up 19 minutes                           k8s_POD_default-backend-445292540-f2l7h_nginx-ingress_8d8ff3b4-7928-11e7-87d8-0a1a0e915450_0
e9e2e64d22b5        weaveworks/weave-kube@sha256:77ffa5e6d1c471e1d921d110e19b579d2c78879b53ac09d7732e5afe441074d2                     "/home/weave/launch.s"   About an hour ago   Up About an hour                        k8s_weave_weave-net-m7fr1_kube-system_208d45ea-791d-11e7-87d8-0a1a0e915450_1
56a3e8d8637b        weaveworks/weave-npc@sha256:5feb89098e84258afaadd878c41e5029ff1baa68579fe75cfca275b24caa4020                      "/usr/bin/weave-npc"     About an hour ago   Up About an hour                        k8s_weave-npc_weave-net-m7fr1_kube-system_208d45ea-791d-11e7-87d8-0a1a0e915450_0
1017042631bd        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 About an hour ago   Up About an hour                        k8s_POD_weave-net-m7fr1_kube-system_208d45ea-791d-11e7-87d8-0a1a0e915450_0
core@ip-10-240-31-58-sandbox-node-lc ~ $ docker exec -it b8329370ff96 bin/bash
```

**Comment by rasheedamir** [comment]
```
11d537383dc5        prom/prometheus@sha256:359aa4eb4f210f6012ac412bc48ea450e2d30fd23a2652d3df6bc311f1936c73                           "/bin/prometheus -con"   2 hours ago         Up 2 hours                              k8s_prometheus_prometheus-1485758666-71hb4_digitaldealer_89520f59-7929-11e7-87d8-0a1a0e915450_3
5a15882a472f        jimmidyson/configmap-reload@sha256:2d40c2eaa6f435b2511d0cfc5f6c0a681eeb2eaa455a5d5ac25f88ce5139986e               "/configmap-reload -v"   2 hours ago         Up 2 hours                              k8s_configmap-reload_prometheus-1485758666-71hb4_digitaldealer_89520f59-7929-11e7-87d8-0a1a0e915450_0
f06d8dadf1fc        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 2 hours ago         Up 2 hours                              k8s_POD_prometheus-1485758666-71hb4_digitaldealer_89520f59-7929-11e7-87d8-0a1a0e915450_0
844ef7e0fc26        registry@sha256:f5552e60ffd56fecbe2f04b61a3089a9cd755bd9352b6b5ab22cf2208af6a3a8                                  "/entrypoint.sh /etc/"   2 hours ago         Up 2 hours                              k8s_fabric8-docker-registry_fabric8-docker-registry-125311296-pgfv3_digitaldealer_a69239ad-7928-11e7-87d8-0a1a0e915450_0
81bc94affefa        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 2 hours ago         Up 2 hours                              k8s_POD_fabric8-docker-registry-125311296-pgfv3_digitaldealer_a69239ad-7928-11e7-87d8-0a1a0e915450_0
ab3f9e12f235        fabric8/jenkinshift@sha256:1ff07e6098cf1c40cb3bd72b8aff6e977b7791ad3aa4b6df660fbf5a29ee36dc                       "/bin/sh -c jenkinshi"   2 hours ago         Up 2 hours                              k8s_jenkinshift_fabric8-3873669821-dnt3v_digitaldealer_aa096167-7928-11e7-87d8-0a1a0e915450_0
06fa5cea7f46        fabric8/fabric8-console@sha256:620727abe356f9c6e82f59c2778e6f93e32f81576385b179fa6b730221c88334                   "/kuisp -p 9090 -c /s"   2 hours ago         Up 2 hours                              k8s_fabric8_fabric8-3873669821-dnt3v_digitaldealer_aa096167-7928-11e7-87d8-0a1a0e915450_0
b8329370ff96        fabric8/exposecontroller@sha256:598c8bf1ae03a8601d1dfbe9ac9889d1654c8c816d76f88cb0a39882ed884b7e                  "/exposecontroller"      2 hours ago         Up 2 hours                              k8s_exposecontroller_exposecontroller-3416897539-swh39_digitaldealer_ad30626d-7928-11e7-87d8-0a1a0e915450_0
197a1cb1b247        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 2 hours ago         Up 2 hours                              k8s_POD_exposecontroller-3416897539-swh39_digitaldealer_ad30626d-7928-11e7-87d8-0a1a0e915450_0
71f76dfd1dfd        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 2 hours ago         Up 2 hours                              k8s_POD_fabric8-3873669821-dnt3v_digitaldealer_aa096167-7928-11e7-87d8-0a1a0e915450_0
cd9932f805e2        prom/node-exporter@sha256:ffc3e0adf58771cb2097aa0b074a6fe68b4925ba75c2e1c41f41ae656eebee11                        "/bin/node_exporter -"   2 hours ago         Up 2 hours                              k8s_node-exporter_node-exporter-v5nb8_digitaldealer_a9307d07-7928-11e7-87d8-0a1a0e915450_0
d66b7efc70b0        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 2 hours ago         Up 2 hours                              k8s_POD_node-exporter-v5nb8_digitaldealer_a9307d07-7928-11e7-87d8-0a1a0e915450_0
1b64010ae919        fabric8/fluentd-kubernetes@sha256:46bef4e8e726dee32600658d784244ee92fee7b84530315ca0a3e347e4096fd4                "/start-fluentd"         2 hours ago         Up 2 hours                              k8s_fluentd_fluentd-mtrk8_digitaldealer_a7b94cd9-7928-11e7-87d8-0a1a0e915450_0
f15146e07344        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 2 hours ago         Up 2 hours                              k8s_POD_fluentd-mtrk8_digitaldealer_a7b94cd9-7928-11e7-87d8-0a1a0e915450_0
1c037c60fc7a        gcr.io/google_containers/defaultbackend@sha256:ee3aa1187023d0197e3277833f19d9ef7df26cee805fef32663e06c7412239f9   "/server"                2 hours ago         Up 2 hours                              k8s_default-backend_default-backend-445292540-f2l7h_nginx-ingress_8d8ff3b4-7928-11e7-87d8-0a1a0e915450_0
cb4a9464f1f4        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 2 hours ago         Up 2 hours                              k8s_POD_default-backend-445292540-f2l7h_nginx-ingress_8d8ff3b4-7928-11e7-87d8-0a1a0e915450_0
e9e2e64d22b5        weaveworks/weave-kube@sha256:77ffa5e6d1c471e1d921d110e19b579d2c78879b53ac09d7732e5afe441074d2                     "/home/weave/launch.s"   3 hours ago         Up 3 hours                              k8s_weave_weave-net-m7fr1_kube-system_208d45ea-791d-11e7-87d8-0a1a0e915450_1
56a3e8d8637b        weaveworks/weave-npc@sha256:5feb89098e84258afaadd878c41e5029ff1baa68579fe75cfca275b24caa4020                      "/usr/bin/weave-npc"     3 hours ago         Up 3 hours                              k8s_weave-npc_weave-net-m7fr1_kube-system_208d45ea-791d-11e7-87d8-0a1a0e915450_0
1017042631bd        gcr.io/google_containers/pause-amd64:3.0                                                                          "/pause"                 3 hours ago         Up 3 hours                              k8s_POD_weave-net-m7fr1_kube-system_208d45ea-791d-11e7-87d8-0a1a0e915450_0
```

**Comment by hazim1093** [comment]
Not reproducible, it probably appeared because `kubedns` was not submitted to kubernetes
